[instance_perl5]
module=perl5
perl5_file=test_cmodule.pl
perl5_source_sub=source
perl5_source_interval_ms=1500
perl5_do_include_build_directories=yes

[instance_cmodule]
module=cmodule
senders=instance_perl5
cmodule_name=sound_display
cmodule_config_function=config
cmodule_source_function=source
cmodule_process_function=process
cmodule_cleanup_function=cleanup
cmodule_custom_setting=custom

[instance_raw]
module=raw
senders=instance_cmodule
raw_print_data=yes
