[instance_ffmpeg]
module=ffmpeg
ffmpeg_output_directory=/var/lib/mass-storage
ffmpeg_filename_format=timestamp
ffmpeg_duration_s=900
ffmpeg_filter_scale=1920x1080
ffmpeg_report_messages=yes

[instance_directory_done]
module=directory
directory_directory=/var/lib/mass-storage
directory_prefix=done-

[instance_directory_out]
module=directory
directory_directory=/var/lib/mass-storage
directory_prefix=out-

(METHODS)
H ffmpeg_filename
D process_ffmpeg APPLY
NOT
D process_directory APPLY
POP

[instance_perl5]
module=perl5
senders=instance_ffmpeg,instance_directory_done,instance_directory_out
methods=(METHODS)
methods_direct_dispatch=yes
perl5_file=misc/test_configs/rrr_ffmpeg_capture.pl
perl5_do_include_build_directories=yes

[instance_raw]
module=raw
senders=instance_perl5
raw_print_data=yes
